repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.243
    hooks:
      - id: ruff
        exclude: _vendor|vendored
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy