repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        exclude: _vendor|vendored
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: .*\.md
    - id: debug-statements
    - id: mixed-line-ending
